version: '3'
services:
  database:
    container_name: webservices-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      webservices-network:
        ipv4_address: 172.14.0.2

networks:
  webservices-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.14.0.0/24
